spring.application.name=api

# Server Port
server.port=8080

# Database Connection
# Master Database Configuration
app.datasource.master.jdbcUrl=jdbc:mysql://localhost:3306/dairy_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
app.datasource.master.username=root
app.datasource.master.password=root

# Tenant 1 Database Configuration
app.datasource.national.jdbcUrl=jdbc:mysql://localhost:3306/national_dairy_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
app.datasource.national.username=root
app.datasource.national.password=root

# Tenant 2 Database Configuration
app.datasource.sunrise.jdbcUrl=jdbc:mysql://localhost:3306/sunrise_dairy_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
app.datasource.sunrise.username=root
app.datasource.sunrise.password=root
# Hibernate / JPA Settings
# 'update' automatically creates/updates your database tables based on your Java Entities
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Twilio SMS Gateway Credentials
twilio.account.sid=YOUR_SID_HERE
twilio.auth.token=YOUR_TOKEN_HERE
twilio.phone.number=YOUR_NUMBER_HERE
